//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_movimento
    {
        public int id_movimento { get; set; }
        public short tipo_movimento { get; set; }
        public System.DateTime data_movimento { get; set; }
        public decimal valor_movimento { get; set; }
        public string obs_movimento { get; set; }
        public int id_categoria { get; set; }
        public int id_empresa { get; set; }
        public int id_conta { get; set; }
        public int id_usuario { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_conta tb_conta { get; set; }
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
